### ISSUE TITLE
rename functions

### ISSUE THREAD

**Issue by jyuu** [jyuu/butcher#55]
Based on r-design discussion "but more importantly, I think I'd recommend object-verb rather than verb-object because it leads to better autocomplete" 

Change all the sub axe functions to begin with object-axe

**Comment by DavisVaughan** [comment]
oooh i think this is the exception though. because the main verb in this package is `axe`, so you'll be thinking "okay i want to axe, now _what_ can i axe". so autocomplete would let you do `axe_<tab>` and see the things you can axe.

I would agree that we should switch if we had multiple `env_axe()` `env_prune()` `env_destroy()` type of functions.
